### ISSUE TITLE
Block Entity Server Crash

### ISSUE THREAD

**Issue by vaylor27** [Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.18.1#16]
The server crashes when there is a Block Entity. Does it have to do with 
		// Wrap our factory in vanilla's factory; it will not be public for users.
		// noinspection Convert2MethodRef - Must be a lambda or else dedicated server will crash

in ScreenHandlerRegistry? How should I fix this

**Comment by Kaupenjoe** [comment]
I fixed that bug in a recent bug fix commit: 57a2138aa11e7a6adf35776845dd06b08e8c2725
hopefully that helps :)

**Comment by vaylor27** [comment]
THANK YOU SO MUCH!!!
