### ISSUE TITLE
Villager Types don't work in 1.19

### ISSUE THREAD

**Issue by vaylor27** [Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.18.1#18]
I updated my mod to 1.19 (I had trouble with the villagers so I looked at how you did it in a recent commit I do still watch the videos as well:)). And it does not work

**Comment by ghost** [comment]
> I updated my mod to 1.19 (I had trouble with the villagers so I looked at how you did it in a recent commit I do still watch the videos as well:)). And it does not work

add it to the acquirable_job_sites tag

**Comment by vaylor27** [comment]
Thank You!!!!!
