### ISSUE TITLE
Can't launch client in Getting Started tutorial

### ISSUE THREAD

**Issue by LuciusOfLegend** [Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.18.1#4]
Hi, I'm having trouble starting my client.  I tried my best to follow your steps, but I'm getting 4 errors in addition to the one about not being logged into a Minecraft account.  Here they are:

   > Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401 (Just the normal account error)

   > Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 
   > 'tutorialmod'

   > Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: 
   > net.luciusoflegend.tutorialmod.TutorialMod

   > Caused by: java.lang.ClassNotFoundException: net.luciusoflegend.tutorialmod.TutorialMod

   > Execution failed for task ':runClient'.
   > Process 'command '/usr/lib/jvm/java-17-temurin/bin/java'' finished with non-zero exit value 255

I got the stacktrace, which you will have to download as a .txt cuz I didn't want to clutter things up:

[Stacktrace.txt](https://github.com/Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.18.1/files/8477302/Stacktrace.txt)

Those are the errors, I hope you can help me figure this out.  Thanks for making the great tutorial series!

**Comment by SirEnder125** [comment]
Hey! Just read the issue, because I was curious, and I think if you upload the fabric.mod.json, it may help figure out what your problem is!

**Comment by LuciusOfLegend** [comment]
Oh.  I was going to try and see the errors again and look in the mod json myself, since I have some prior coding experience, but It looks like I fixed the issue on my own yesterday haha.
