### ISSUE TITLE
[Question]  How to build my mod into a .jar file?

### ISSUE THREAD

**Issue by LuciusOfLegend** [Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.18.1#5]
Hi, i wanted to know how to turn my mod into a .jar file so I can use it with other mods.

**Comment by SirEnder125** [comment]
Kaupenjoe's fabric 1.17.1 series had a tutorial on how to do this, and I would assume it still works the same way!

https://youtu.be/Z2h-Fc5ewCo

**Comment by LuciusOfLegend** [comment]
Thanks.  I noticed that you are just hanging around this repository helping people who need it.  Just wanna say that's pretty cool.
